server:
  port: 8086
spring:
  application:
    name: JSupervisor
  task:
    execution:
      thread-name-prefix: "process-pool-"
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 25

logging:
  level:
    root: info
    sun:
      rmi: info
    javax:
      management:
        remote:
          rmi: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
json-config-schema:
  description: ${spring.application.name}
  title: JSupervisor configuration

ui-config:
  ui-status-class:
    aborted: bg-warning
    failed: bg-danger
    finished: bg-success
    not-started: bg-secondary
    running: bg-primary
    starting: bg-info
    stopped: bg-success
    stopping: bg-info
    unknown: bg-info
    healthy: bg-success
    unhealthy: bg-warning
---
spring:
  config:
    activate:
      on-profile: test

jsupervisor:
  node-name: local
  process:
    test:
      application-log:
      command: "java"
      working-directory: "work"
      stdout-logfile: test-stdout.log
      stderr-logfile: test-stderr.log
      args:
        - "-version"
      shutdown-timeout: 1m
    sleep:
      command: "sleep"
      working-directory: "work"
      stdout-logfile: sleep-stdout.log
      stderr-logfile: sleep-stderr.log
      args:
        - "10"
ui-config:
  ui-status-class:
    aborted: bg-warning
    failed: bg-danger
    finished: bg-success
    not-started: bg-secondary
    running: bg-primary
    starting: bg-info
    stopped: bg-success
    stopping: bg-info
    unknown: bg-info
    healthy: bg-success
    unhealthy: bg-warning






