$schema: "http://127.0.0.1:8086/actuator/config-schema.yaml"
server:
  port: 8086
spring:
  application:
    name: simple-boot-supervisor
  task:
    execution:
      thread-name-prefix: "process-pool-"
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 25

process:
  name: test
  command: "java"
  working-directory: "/Users/alex.mondshain/IdeaProjects/spring-boot-playground/spring-boot-supervisor/work"
  stdout-logfile: ${process.working-directory}/stdout.log
  stderr-logfile: ${process.working-directory}/error.log
  args:
    - "-version"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

logging:
  level:
    root: info
    sun:
      rmi: info
    javax:
      management:
        remote:
          rmi: info

supervisor:
  node-name: local
  process:
    test:
      command: "java"
      working-directory: "../work"
      stdout-logfile: test-stdout.log
      stderr-logfile: test-stderr.log
      args:
      - "-version"
      shutdown-timeout: 1m
    sleep:
      command: "sleep"
      working-directory: "../work"
      stdout-logfile: sleep-stdout.log
      stderr-logfile: sleep-stderr.log
      args:
        - "10"
    testapp1:
      actuator-url: http://localhost:8080/actuator
      command: "java"
      working-directory: "../spring-boot-test-app"
      stdout-logfile: testapp1-stdout.log
      stderr-logfile: testapp1-error.log
      url: http://localhost:8080/
      args:
        - "-Dspring.profiles.active=srv1"
        - "-Dspring.application.name=testapp1"
        - "-jar"
        - target/spring-boot-test-app-0.0.1-SNAPSHOT.jar
    testapp2:
      command: "java"
      working-directory: "../spring-boot-test-app"
      stdout-logfile: testapp2-stdout.log
      stderr-logfile: testapp2-error.log
      url: http://localhost:8081/
      env:
        SPRING_PROFILES_ACTIVE: srv2
        SPRING_APPLICATION_NAME: testapp1
      args:
        - "-jar"
        - target/spring-boot-test-app-0.0.1-SNAPSHOT.jar






