/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.alexmond.jsupervisor.client.api;

import com.fasterxml.jackson.core.type.TypeReference;
import org.alexmond.jsupervisor.client.invoker.*;
import org.alexmond.jsupervisor.client.model.EntityModelProcessEventEntry;
import org.alexmond.jsupervisor.client.model.PagedModelEntityModelProcessEventEntry;
import org.alexmond.jsupervisor.client.model.ProcessEventEntryRequestBody;

import java.util.*;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ProcessEventEntryEntityControllerApi extends BaseApi {

    public ProcessEventEntryEntityControllerApi() {
        super(Configuration.getDefaultApiClient());
    }

    public ProcessEventEntryEntityControllerApi(ApiClient apiClient) {
        super(apiClient);
    }

    /**
     *
     * delete-processevententry
     *
     * @param id (required)
     * @throws ApiException if fails to make API call
     */
    public void deleteItemResourceProcessevententryDelete(@jakarta.annotation.Nonnull String id) throws ApiException {
        this.deleteItemResourceProcessevententryDelete(id, Collections.emptyMap());
    }


    /**
     *
     * delete-processevententry
     *
     * @param id                (required)
     * @param additionalHeaders additionalHeaders for this call
     * @throws ApiException if fails to make API call
     */
    public void deleteItemResourceProcessevententryDelete(@jakarta.annotation.Nonnull String id, Map<String, String> additionalHeaders) throws ApiException {
        Object localVarPostBody = null;

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(400, "Missing the required parameter 'id' when calling deleteItemResourceProcessevententryDelete");
        }

        // create path and map variables
        String localVarPath = "/api/v1/processEventEntries/{id}"
                .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

        StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
        String localVarQueryParameterBaseName;
        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();


        localVarHeaderParams.putAll(additionalHeaders);


        final String[] localVarAccepts = {

        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

        String[] localVarAuthNames = new String[]{};

        apiClient.invokeAPI(
                localVarPath,
                "DELETE",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarQueryStringJoiner.toString(),
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAccept,
                localVarContentType,
                localVarAuthNames,
                null
        );
    }

    /**
     *
     * get-processevententry
     *
     * @param page Zero-based page index (0..N) (optional, default to 0)
     * @param size The size of the page to be returned (optional, default to 20)
     * @param sort Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. (optional)
     * @return PagedModelEntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public PagedModelEntityModelProcessEventEntry getCollectionResourceProcessevententryGet(@jakarta.annotation.Nullable Integer page, @jakarta.annotation.Nullable Integer size, @jakarta.annotation.Nullable List<String> sort) throws ApiException {
        return this.getCollectionResourceProcessevententryGet(page, size, sort, Collections.emptyMap());
    }


    /**
     *
     * get-processevententry
     *
     * @param page              Zero-based page index (0..N) (optional, default to 0)
     * @param size              The size of the page to be returned (optional, default to 20)
     * @param sort              Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. (optional)
     * @param additionalHeaders additionalHeaders for this call
     * @return PagedModelEntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public PagedModelEntityModelProcessEventEntry getCollectionResourceProcessevententryGet(@jakarta.annotation.Nullable Integer page, @jakarta.annotation.Nullable Integer size, @jakarta.annotation.Nullable List<String> sort, Map<String, String> additionalHeaders) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/processEventEntries";

        StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
        String localVarQueryParameterBaseName;
        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        localVarQueryParams.addAll(apiClient.parameterToPair("page", page));
        localVarQueryParams.addAll(apiClient.parameterToPair("size", size));
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("multi", "sort", sort));

        localVarHeaderParams.putAll(additionalHeaders);


        final String[] localVarAccepts = {
                "*/*", "application/x-spring-data-compact+json", "text/uri-list"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

        String[] localVarAuthNames = new String[]{};

        TypeReference<PagedModelEntityModelProcessEventEntry> localVarReturnType = new TypeReference<PagedModelEntityModelProcessEventEntry>() {
        };
        return apiClient.invokeAPI(
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarQueryStringJoiner.toString(),
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAccept,
                localVarContentType,
                localVarAuthNames,
                localVarReturnType
        );
    }

    /**
     *
     * get-processevententry
     *
     * @param id (required)
     * @return EntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public EntityModelProcessEventEntry getItemResourceProcessevententryGet(@jakarta.annotation.Nonnull String id) throws ApiException {
        return this.getItemResourceProcessevententryGet(id, Collections.emptyMap());
    }


    /**
     *
     * get-processevententry
     *
     * @param id                (required)
     * @param additionalHeaders additionalHeaders for this call
     * @return EntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public EntityModelProcessEventEntry getItemResourceProcessevententryGet(@jakarta.annotation.Nonnull String id, Map<String, String> additionalHeaders) throws ApiException {
        Object localVarPostBody = null;

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(400, "Missing the required parameter 'id' when calling getItemResourceProcessevententryGet");
        }

        // create path and map variables
        String localVarPath = "/api/v1/processEventEntries/{id}"
                .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

        StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
        String localVarQueryParameterBaseName;
        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();


        localVarHeaderParams.putAll(additionalHeaders);


        final String[] localVarAccepts = {
                "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

        String[] localVarAuthNames = new String[]{};

        TypeReference<EntityModelProcessEventEntry> localVarReturnType = new TypeReference<EntityModelProcessEventEntry>() {
        };
        return apiClient.invokeAPI(
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarQueryStringJoiner.toString(),
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAccept,
                localVarContentType,
                localVarAuthNames,
                localVarReturnType
        );
    }

    /**
     *
     * patch-processevententry
     *
     * @param id                           (required)
     * @param processEventEntryRequestBody (required)
     * @return EntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public EntityModelProcessEventEntry patchItemResourceProcessevententryPatch(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull ProcessEventEntryRequestBody processEventEntryRequestBody) throws ApiException {
        return this.patchItemResourceProcessevententryPatch(id, processEventEntryRequestBody, Collections.emptyMap());
    }


    /**
     *
     * patch-processevententry
     *
     * @param id                           (required)
     * @param processEventEntryRequestBody (required)
     * @param additionalHeaders            additionalHeaders for this call
     * @return EntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public EntityModelProcessEventEntry patchItemResourceProcessevententryPatch(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull ProcessEventEntryRequestBody processEventEntryRequestBody, Map<String, String> additionalHeaders) throws ApiException {
        Object localVarPostBody = processEventEntryRequestBody;

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(400, "Missing the required parameter 'id' when calling patchItemResourceProcessevententryPatch");
        }

        // verify the required parameter 'processEventEntryRequestBody' is set
        if (processEventEntryRequestBody == null) {
            throw new ApiException(400, "Missing the required parameter 'processEventEntryRequestBody' when calling patchItemResourceProcessevententryPatch");
        }

        // create path and map variables
        String localVarPath = "/api/v1/processEventEntries/{id}"
                .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

        StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
        String localVarQueryParameterBaseName;
        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();


        localVarHeaderParams.putAll(additionalHeaders);


        final String[] localVarAccepts = {
                "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

        final String[] localVarContentTypes = {
                "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

        String[] localVarAuthNames = new String[]{};

        TypeReference<EntityModelProcessEventEntry> localVarReturnType = new TypeReference<EntityModelProcessEventEntry>() {
        };
        return apiClient.invokeAPI(
                localVarPath,
                "PATCH",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarQueryStringJoiner.toString(),
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAccept,
                localVarContentType,
                localVarAuthNames,
                localVarReturnType
        );
    }

    /**
     *
     * create-processevententry
     *
     * @param processEventEntryRequestBody (required)
     * @return EntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public EntityModelProcessEventEntry postCollectionResourceProcessevententryPost(@jakarta.annotation.Nonnull ProcessEventEntryRequestBody processEventEntryRequestBody) throws ApiException {
        return this.postCollectionResourceProcessevententryPost(processEventEntryRequestBody, Collections.emptyMap());
    }


    /**
     *
     * create-processevententry
     *
     * @param processEventEntryRequestBody (required)
     * @param additionalHeaders            additionalHeaders for this call
     * @return EntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public EntityModelProcessEventEntry postCollectionResourceProcessevententryPost(@jakarta.annotation.Nonnull ProcessEventEntryRequestBody processEventEntryRequestBody, Map<String, String> additionalHeaders) throws ApiException {
        Object localVarPostBody = processEventEntryRequestBody;

        // verify the required parameter 'processEventEntryRequestBody' is set
        if (processEventEntryRequestBody == null) {
            throw new ApiException(400, "Missing the required parameter 'processEventEntryRequestBody' when calling postCollectionResourceProcessevententryPost");
        }

        // create path and map variables
        String localVarPath = "/api/v1/processEventEntries";

        StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
        String localVarQueryParameterBaseName;
        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();


        localVarHeaderParams.putAll(additionalHeaders);


        final String[] localVarAccepts = {
                "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

        final String[] localVarContentTypes = {
                "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

        String[] localVarAuthNames = new String[]{};

        TypeReference<EntityModelProcessEventEntry> localVarReturnType = new TypeReference<EntityModelProcessEventEntry>() {
        };
        return apiClient.invokeAPI(
                localVarPath,
                "POST",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarQueryStringJoiner.toString(),
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAccept,
                localVarContentType,
                localVarAuthNames,
                localVarReturnType
        );
    }

    /**
     *
     * update-processevententry
     *
     * @param id                           (required)
     * @param processEventEntryRequestBody (required)
     * @return EntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public EntityModelProcessEventEntry putItemResourceProcessevententryPut(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull ProcessEventEntryRequestBody processEventEntryRequestBody) throws ApiException {
        return this.putItemResourceProcessevententryPut(id, processEventEntryRequestBody, Collections.emptyMap());
    }


    /**
     *
     * update-processevententry
     *
     * @param id                           (required)
     * @param processEventEntryRequestBody (required)
     * @param additionalHeaders            additionalHeaders for this call
     * @return EntityModelProcessEventEntry
     * @throws ApiException if fails to make API call
     */
    public EntityModelProcessEventEntry putItemResourceProcessevententryPut(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull ProcessEventEntryRequestBody processEventEntryRequestBody, Map<String, String> additionalHeaders) throws ApiException {
        Object localVarPostBody = processEventEntryRequestBody;

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(400, "Missing the required parameter 'id' when calling putItemResourceProcessevententryPut");
        }

        // verify the required parameter 'processEventEntryRequestBody' is set
        if (processEventEntryRequestBody == null) {
            throw new ApiException(400, "Missing the required parameter 'processEventEntryRequestBody' when calling putItemResourceProcessevententryPut");
        }

        // create path and map variables
        String localVarPath = "/api/v1/processEventEntries/{id}"
                .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

        StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
        String localVarQueryParameterBaseName;
        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();


        localVarHeaderParams.putAll(additionalHeaders);


        final String[] localVarAccepts = {
                "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

        final String[] localVarContentTypes = {
                "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

        String[] localVarAuthNames = new String[]{};

        TypeReference<EntityModelProcessEventEntry> localVarReturnType = new TypeReference<EntityModelProcessEventEntry>() {
        };
        return apiClient.invokeAPI(
                localVarPath,
                "PUT",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarQueryStringJoiner.toString(),
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAccept,
                localVarContentType,
                localVarAuthNames,
                localVarReturnType
        );
    }

    @Override
    public <T> T invokeAPI(String url, String method, Object request, TypeReference<T> returnType, Map<String, String> additionalHeaders) throws ApiException {
        String localVarPath = url.replace(apiClient.getBaseURL(), "");
        StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        localVarHeaderParams.putAll(additionalHeaders);

        final String[] localVarAccepts = {
                "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

        final String[] localVarContentTypes = {
                "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

        String[] localVarAuthNames = new String[]{};

        return apiClient.invokeAPI(
                localVarPath,
                method,
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarQueryStringJoiner.toString(),
                request,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAccept,
                localVarContentType,
                localVarAuthNames,
                returnType
        );
    }
}
