server:
  port: 8086
spring:
  application:
    name: simple-boot-supervisor
  task:
    execution:
      thread-name-prefix: "process-pool-"
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 25

logging:
  level:
    root: info
    sun:
      rmi: info
    javax:
      management:
        remote:
          rmi: info

---
spring:
  config:
    activate:
      on-profile: test

supervisor:
  node-name: local
  process:
    test:
      command: "java"
      working-directory: "work"
      stdout-logfile: test-stdout.log
      stderr-logfile: test-stderr.log
      args:
        - "-version"
      shutdown-timeout: 1m
    sleep:
      command: "sleep"
      working-directory: "work"
      stdout-logfile: sleep-stdout.log
      stderr-logfile: sleep-stderr.log
      args:
        - "10"
#  <span class="badge badge-primary">Primary</span>
#  <span class="badge badge-secondary">Secondary</span>
#  <span class="badge badge-success">Success</span>
#  <span class="badge badge-danger">Danger</span>
#  <span class="badge badge-warning">Warning</span>
#  <span class="badge badge-info">Info</span>
#  <span class="badge badge-light">Light</span>
#  <span class="badge badge-dark">Dark</span>
  ui-config:
    ui-status-class:
      aborted: bg-warning
      failed: bg-danger
      finished: bg-success
      not-started: bg-secondary
      running: bg-primary
      starting: bg-info
      stopped: bg-success
      unknown: bg-info
      healthy: bg-success
      unhealthy: bg-warning






