/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.api;

import org.alexmond.jsupervisor.client.invoker.ApiException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * API tests for BulkProcessOperationsApi
 */
@Disabled
public class BulkProcessOperationsApiTest {

    private final BulkProcessOperationsApi api = new BulkProcessOperationsApi();

    /**
     * Restart all processes
     *
     * Restart all configured processes
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restartAllTest() throws ApiException {
        api.restartAll();

        // TODO: test validations
    }
    /**
     * Start all processes
     *
     * Start all configured processes that are not currently running
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void startAllTest() throws ApiException {
        api.startAll();

        // TODO: test validations
    }
    /**
     * Stop all processes
     *
     * Stop all currently running processes
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void stopAllTest() throws ApiException {
        api.stopAll();

        // TODO: test validations
    }
}
