/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.api;

import org.alexmond.jsupervisor.client.invoker.ApiException;
import org.alexmond.jsupervisor.client.model.Page;
import org.alexmond.jsupervisor.client.model.PageProcessEventEntry;
import org.alexmond.jsupervisor.client.model.ProcessEventEntry;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.Map;

/**
 * API tests for EventManagementApi
 */
@Disabled
public class EventManagementApiTest {

    private final EventManagementApi api = new EventManagementApi();

    /**
     * Get event by ID
     * <p>
     * Retrieves detailed information about a specific process event
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventByIdTest() throws ApiException {
        Long id = null;
        ProcessEventEntry response = api.getEventById(id);

        // TODO: test validations
    }

    /**
     * Get paginated events
     * <p>
     * Retrieves a paginated list of all process events with customizable sorting
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventsTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        String sortBy = null;
        String sortDirection = null;
        Page response = api.getEvents(page, size, sortBy, sortDirection);

        // TODO: test validations
    }

    /**
     * Get events by process name
     * <p>
     * Retrieves paginated events for a specific process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventsByProcessTest() throws ApiException {
        String processName = null;
        Integer page = null;
        Integer size = null;
        String sortBy = null;
        String sortDirection = null;
        PageProcessEventEntry response = api.getEventsByProcess(processName, page, size, sortBy, sortDirection);

        // TODO: test validations
    }

    /**
     * Get events by status
     * <p>
     * Retrieves paginated events matching a specific process status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventsByStatusTest() throws ApiException {
        String status = null;
        Integer page = null;
        Integer size = null;
        String sortBy = null;
        String sortDirection = null;
        PageProcessEventEntry response = api.getEventsByStatus(status, page, size, sortBy, sortDirection);

        // TODO: test validations
    }

    /**
     * Get total event count
     * <p>
     * Returns the total number of events in the system
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTotalEventsCountTest() throws ApiException {
        Map<String, Long> response = api.getTotalEventsCount();

        // TODO: test validations
    }
}
