/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses. 
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.api;

import org.alexmond.jsupervisor.client.invoker.ApiException;
import org.alexmond.jsupervisor.client.model.ErrorResponse;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * API tests for GroupProcessOperationsApi
 */
@Disabled
public class GroupProcessOperationsApiTest {

    private final GroupProcessOperationsApi api = new GroupProcessOperationsApi();

    /**
     * Restart all processes
     *
     * Restart all configured processes
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restartAllTest() throws ApiException {
        api.restartAll();

        // TODO: test validations
    }
    /**
     * Start all processes
     *
     * Start all configured processes that are not currently running
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void startAllTest() throws ApiException {
        api.startAll();

        // TODO: test validations
    }
    /**
     * Stop all processes
     *
     * Stop all currently running processes
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void stopAllTest() throws ApiException {
        api.stopAll();

        // TODO: test validations
    }
}
