/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses. 
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.api;

import org.alexmond.jsupervisor.client.invoker.ApiException;
import org.alexmond.jsupervisor.client.model.ErrorResponse;
import org.alexmond.jsupervisor.client.model.ProcessStatusRest;
import org.alexmond.jsupervisor.client.model.ResponseMessage;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * API tests for ProcessManagementApi
 */
@Disabled
public class ProcessManagementApiTest {

    private final ProcessManagementApi api = new ProcessManagementApi();

    /**
     * List all processes
     *
     * Retrieve status information for all configured processes
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllProcessesTest() throws ApiException {
        List<ProcessStatusRest> response = api.getAllProcesses();

        // TODO: test validations
    }
    /**
     * Get process status
     *
     * Get the current status of a specific process
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProcessStatusTest() throws ApiException {
        String name = null;
        ProcessStatusRest response = api.getProcessStatus(name);

        // TODO: test validations
    }
    /**
     * Restart process
     *
     * Restart a specific process
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restartProcessTest() throws ApiException {
        String name = null;
        api.restartProcess(name);

        // TODO: test validations
    }
    /**
     * Start process
     *
     * Start a specific process
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void startProcessTest() throws ApiException {
        String name = null;
        ResponseMessage response = api.startProcess(name);

        // TODO: test validations
    }
    /**
     * Stop process
     *
     * Stop a specific process
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void stopProcessTest() throws ApiException {
        String name = null;
        api.stopProcess(name);

        // TODO: test validations
    }
}
