/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.api;

import org.alexmond.jsupervisor.client.invoker.ApiException;
import org.alexmond.jsupervisor.client.model.EntityModelProcessEventEntry;
import org.alexmond.jsupervisor.client.model.PagedModelEntityModelProcessEventEntry;
import org.alexmond.jsupervisor.client.model.ProcessEventEntryRequestBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.List;

/**
 * API tests for ProcessEventEntryEntityControllerApi
 */
@Disabled
public class ProcessEventEntryEntityControllerApiTest {

    private final ProcessEventEntryEntityControllerApi api = new ProcessEventEntryEntityControllerApi();

    /**
     * delete-processevententry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteItemResourceProcessevententryDeleteTest() throws ApiException {
        String id = null;
        api.deleteItemResourceProcessevententryDelete(id);

        // TODO: test validations
    }

    /**
     * get-processevententry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCollectionResourceProcessevententryGetTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        PagedModelEntityModelProcessEventEntry response = api.getCollectionResourceProcessevententryGet(page, size, sort);

        // TODO: test validations
    }

    /**
     * get-processevententry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getItemResourceProcessevententryGetTest() throws ApiException {
        String id = null;
        EntityModelProcessEventEntry response = api.getItemResourceProcessevententryGet(id);

        // TODO: test validations
    }

    /**
     * patch-processevententry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchItemResourceProcessevententryPatchTest() throws ApiException {
        String id = null;
        ProcessEventEntryRequestBody processEventEntryRequestBody = null;
        EntityModelProcessEventEntry response = api.patchItemResourceProcessevententryPatch(id, processEventEntryRequestBody);

        // TODO: test validations
    }

    /**
     * create-processevententry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCollectionResourceProcessevententryPostTest() throws ApiException {
        ProcessEventEntryRequestBody processEventEntryRequestBody = null;
        EntityModelProcessEventEntry response = api.postCollectionResourceProcessevententryPost(processEventEntryRequestBody);

        // TODO: test validations
    }

    /**
     * update-processevententry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putItemResourceProcessevententryPutTest() throws ApiException {
        String id = null;
        ProcessEventEntryRequestBody processEventEntryRequestBody = null;
        EntityModelProcessEventEntry response = api.putItemResourceProcessevententryPut(id, processEventEntryRequestBody);

        // TODO: test validations
    }
}
