/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.api;

import org.alexmond.jsupervisor.client.invoker.ApiException;
import org.alexmond.jsupervisor.client.model.CollectionModelEntityModelProcessEventEntry;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * API tests for ProcessEventEntrySearchControllerApi
 */
@Disabled
public class ProcessEventEntrySearchControllerApiTest {

    private final ProcessEventEntrySearchControllerApi api = new ProcessEventEntrySearchControllerApi();

    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeSearchProcessevententryGetTest() throws ApiException {
        String processName = null;
        CollectionModelEntityModelProcessEventEntry response = api.executeSearchProcessevententryGet(processName);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeSearchProcessevententryGet1Test() throws ApiException {
        String status = null;
        CollectionModelEntityModelProcessEventEntry response = api.executeSearchProcessevententryGet1(status);

        // TODO: test validations
    }
}
