/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.api;

import org.alexmond.jsupervisor.client.invoker.ApiException;
import org.alexmond.jsupervisor.client.model.RepresentationModelObject;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for ProfileControllerApi
 */
@Disabled
public class ProfileControllerApiTest {

    private final ProfileControllerApi api = new ProfileControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void descriptorTest() throws ApiException {
        String response = api.descriptor();

        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllFormsOfMetadataTest() throws ApiException {
        RepresentationModelObject response = api.listAllFormsOfMetadata();

        // TODO: test validations
    }
}
