/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.api;

import org.alexmond.jsupervisor.client.invoker.ApiException;
import org.alexmond.jsupervisor.client.model.JsonSchema;
import org.alexmond.jsupervisor.client.model.RepresentationModelObject;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * API tests for ProfileControllerApi
 */
@Disabled
public class ProfileControllerApiTest {

    private final ProfileControllerApi api = new ProfileControllerApi();

    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void descriptorTest() throws ApiException {
        String response = api.descriptor();

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllFormsOfMetadataTest() throws ApiException {
        RepresentationModelObject response = api.listAllFormsOfMetadata();

        // TODO: test validations
    }
}
