/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.api;

import org.alexmond.jsupervisor.client.invoker.ApiException;
import org.alexmond.jsupervisor.client.model.SupervisorRest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * API tests for SupervisorInformationApi
 */
@Disabled
public class SupervisorInformationApiTest {

    private final SupervisorInformationApi api = new SupervisorInformationApi();

    /**
     * Get supervisor info
     *
     * Retrieve basic supervisor information
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSupervisorInfoTest() throws ApiException {
        SupervisorRest response = api.getSupervisorInfo();

        // TODO: test validations
    }
}
