/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AbstractJsonSchemaPropertyObject
 */
class AbstractJsonSchemaPropertyObjectTest {
    private final AbstractJsonSchemaPropertyObject model = new AbstractJsonSchemaPropertyObject();

    /**
     * Model tests for AbstractJsonSchemaPropertyObject
     */
    @Test
    void testAbstractJsonSchemaPropertyObject() {
        // TODO: test AbstractJsonSchemaPropertyObject
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'readOnly'
     */
    @Test
    void readOnlyTest() {
        // TODO: test readOnly
    }

}
