/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.alexmond.jsupervisor.client.model.EntityModelProcessEventEntry;
import org.alexmond.jsupervisor.client.model.Link;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CollectionModelEntityModelProcessEventEntry
 */
class CollectionModelEntityModelProcessEventEntryTest {
    private final CollectionModelEntityModelProcessEventEntry model = new CollectionModelEntityModelProcessEventEntry();

    /**
     * Model tests for CollectionModelEntityModelProcessEventEntry
     */
    @Test
    void testCollectionModelEntityModelProcessEventEntry() {
        // TODO: test CollectionModelEntityModelProcessEventEntry
    }

    /**
     * Test the property 'links'
     */
    @Test
    void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'content'
     */
    @Test
    void contentTest() {
        // TODO: test content
    }

}
