/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for EntityModelProcessEventEntry
 */
class EntityModelProcessEventEntryTest {
    private final EntityModelProcessEventEntry model = new EntityModelProcessEventEntry();

    /**
     * Model tests for EntityModelProcessEventEntry
     */
    @Test
    void testEntityModelProcessEventEntry() {
        // TODO: test EntityModelProcessEventEntry
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'pid'
     */
    @Test
    void pidTest() {
        // TODO: test pid
    }

    /**
     * Test the property 'eventTime'
     */
    @Test
    void eventTimeTest() {
        // TODO: test eventTime
    }

    /**
     * Test the property 'processName'
     */
    @Test
    void processNameTest() {
        // TODO: test processName
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'exitCode'
     */
    @Test
    void exitCodeTest() {
        // TODO: test exitCode
    }

    /**
     * Test the property 'newStatus'
     */
    @Test
    void newStatusTest() {
        // TODO: test newStatus
    }

    /**
     * Test the property 'oldStatus'
     */
    @Test
    void oldStatusTest() {
        // TODO: test oldStatus
    }

    /**
     * Test the property 'processUptime'
     */
    @Test
    void processUptimeTest() {
        // TODO: test processUptime
    }

    /**
     * Test the property 'links'
     */
    @Test
    void linksTest() {
        // TODO: test links
    }

}
