/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.alexmond.jsupervisor.client.model.AbstractJsonSchemaPropertyObject;
import org.alexmond.jsupervisor.client.model.Item;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JsonSchema
 */
class JsonSchemaTest {
    private final JsonSchema model = new JsonSchema();

    /**
     * Model tests for JsonSchema
     */
    @Test
    void testJsonSchema() {
        // TODO: test JsonSchema
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'properties'
     */
    @Test
    void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'requiredProperties'
     */
    @Test
    void requiredPropertiesTest() {
        // TODO: test requiredProperties
    }

    /**
     * Test the property 'definitions'
     */
    @Test
    void definitionsTest() {
        // TODO: test definitions
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property '$schema'
     */
    @Test
    void $schemaTest() {
        // TODO: test $schema
    }

}
