/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for JsonSchema
 */
class JsonSchemaTest {
    private final JsonSchema model = new JsonSchema();

    /**
     * Model tests for JsonSchema
     */
    @Test
    void testJsonSchema() {
        // TODO: test JsonSchema
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'properties'
     */
    @Test
    void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'requiredProperties'
     */
    @Test
    void requiredPropertiesTest() {
        // TODO: test requiredProperties
    }

    /**
     * Test the property 'definitions'
     */
    @Test
    void definitionsTest() {
        // TODO: test definitions
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property '$schema'
     */
    @Test
    void $schemaTest() {
        // TODO: test $schema
    }

}
