/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Link
 */
class LinkTest {
    private final Link model = new Link();

    /**
     * Model tests for Link
     */
    @Test
    void testLink() {
        // TODO: test Link
    }

    /**
     * Test the property 'rel'
     */
    @Test
    void relTest() {
        // TODO: test rel
    }

    /**
     * Test the property 'href'
     */
    @Test
    void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'hreflang'
     */
    @Test
    void hreflangTest() {
        // TODO: test hreflang
    }

    /**
     * Test the property 'media'
     */
    @Test
    void mediaTest() {
        // TODO: test media
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'deprecation'
     */
    @Test
    void deprecationTest() {
        // TODO: test deprecation
    }

    /**
     * Test the property 'profile'
     */
    @Test
    void profileTest() {
        // TODO: test profile
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

}
