/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses. 
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.alexmond.jsupervisor.client.model.PageableObject;
import org.alexmond.jsupervisor.client.model.ProcessEventEntry;
import org.alexmond.jsupervisor.client.model.SortObject;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PageProcessEventEntry
 */
class PageProcessEventEntryTest {
    private final PageProcessEventEntry model = new PageProcessEventEntry();

    /**
     * Model tests for PageProcessEventEntry
     */
    @Test
    void testPageProcessEventEntry() {
        // TODO: test PageProcessEventEntry
    }

    /**
     * Test the property 'totalElements'
     */
    @Test
    void totalElementsTest() {
        // TODO: test totalElements
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    void totalPagesTest() {
        // TODO: test totalPages
    }

    /**
     * Test the property 'first'
     */
    @Test
    void firstTest() {
        // TODO: test first
    }

    /**
     * Test the property 'last'
     */
    @Test
    void lastTest() {
        // TODO: test last
    }

    /**
     * Test the property 'size'
     */
    @Test
    void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'content'
     */
    @Test
    void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'number'
     */
    @Test
    void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'sort'
     */
    @Test
    void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'numberOfElements'
     */
    @Test
    void numberOfElementsTest() {
        // TODO: test numberOfElements
    }

    /**
     * Test the property 'pageable'
     */
    @Test
    void pageableTest() {
        // TODO: test pageable
    }

    /**
     * Test the property 'empty'
     */
    @Test
    void emptyTest() {
        // TODO: test empty
    }

}
