/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for PageableObject
 */
class PageableObjectTest {
    private final PageableObject model = new PageableObject();

    /**
     * Model tests for PageableObject
     */
    @Test
    void testPageableObject() {
        // TODO: test PageableObject
    }

    /**
     * Test the property 'offset'
     */
    @Test
    void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'sort'
     */
    @Test
    void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    void pageNumberTest() {
        // TODO: test pageNumber
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'unpaged'
     */
    @Test
    void unpagedTest() {
        // TODO: test unpaged
    }

    /**
     * Test the property 'paged'
     */
    @Test
    void pagedTest() {
        // TODO: test paged
    }

}
