/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProcessStatusRest
 */
class ProcessStatusRestTest {
    private final ProcessStatusRest model = new ProcessStatusRest();

    /**
     * Model tests for ProcessStatusRest
     */
    @Test
    void testProcessStatusRest() {
        // TODO: test ProcessStatusRest
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'pid'
     */
    @Test
    void pidTest() {
        // TODO: test pid
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'exitCode'
     */
    @Test
    void exitCodeTest() {
        // TODO: test exitCode
    }

    /**
     * Test the property 'processRuntime'
     */
    @Test
    void processRuntimeTest() {
        // TODO: test processRuntime
    }

    /**
     * Test the property 'processUptime'
     */
    @Test
    void processUptimeTest() {
        // TODO: test processUptime
    }

    /**
     * Test the property 'stdoutLogfile'
     */
    @Test
    void stdoutLogfileTest() {
        // TODO: test stdoutLogfile
    }

    /**
     * Test the property 'stderrLogfile'
     */
    @Test
    void stderrLogfileTest() {
        // TODO: test stderrLogfile
    }

    /**
     * Test the property 'failedErrorLog'
     */
    @Test
    void failedErrorLogTest() {
        // TODO: test failedErrorLog
    }

    /**
     * Test the property 'alive'
     */
    @Test
    void aliveTest() {
        // TODO: test alive
    }

}
