/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses. 
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ProcessStatusRest
 */
class ProcessStatusInfoTest {
    private final ProcessStatusInfo model = new ProcessStatusInfo();

    /**
     * Model tests for ProcessStatusRest
     */
    @Test
    void testProcessStatusRest() {
        // TODO: test ProcessStatusRest
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'pid'
     */
    @Test
    void pidTest() {
        // TODO: test pid
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'exitCode'
     */
    @Test
    void exitCodeTest() {
        // TODO: test exitCode
    }

    /**
     * Test the property 'processRuntime'
     */
    @Test
    void processRuntimeTest() {
        // TODO: test processRuntime
    }

    /**
     * Test the property 'processUptime'
     */
    @Test
    void processUptimeTest() {
        // TODO: test processUptime
    }

    /**
     * Test the property 'stdoutLogfile'
     */
    @Test
    void stdoutLogfileTest() {
        // TODO: test stdoutLogfile
    }

    /**
     * Test the property 'stderrLogfile'
     */
    @Test
    void stderrLogfileTest() {
        // TODO: test stderrLogfile
    }

    /**
     * Test the property 'failedErrorLog'
     */
    @Test
    void failedErrorLogTest() {
        // TODO: test failedErrorLog
    }

    /**
     * Test the property 'alive'
     */
    @Test
    void aliveTest() {
        // TODO: test alive
    }

}
