/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses. 
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SortObject
 */
class SortObjectTest {
    private final SortObject model = new SortObject();

    /**
     * Model tests for SortObject
     */
    @Test
    void testSortObject() {
        // TODO: test SortObject
    }

    /**
     * Test the property 'empty'
     */
    @Test
    void emptyTest() {
        // TODO: test empty
    }

    /**
     * Test the property 'sorted'
     */
    @Test
    void sortedTest() {
        // TODO: test sorted
    }

    /**
     * Test the property 'unsorted'
     */
    @Test
    void unsortedTest() {
        // TODO: test unsorted
    }

}
