/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for SupervisorRest
 */
class SupervisorRestTest {
    private final SupervisorRest model = new SupervisorRest();

    /**
     * Model tests for SupervisorRest
     */
    @Test
    void testSupervisorRest() {
        // TODO: test SupervisorRest
    }

    /**
     * Test the property 'nodeName'
     */
    @Test
    void nodeNameTest() {
        // TODO: test nodeName
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'physicalMemory'
     */
    @Test
    void physicalMemoryTest() {
        // TODO: test physicalMemory
    }

    /**
     * Test the property 'physicalCpu'
     */
    @Test
    void physicalCpuTest() {
        // TODO: test physicalCpu
    }

    /**
     * Test the property 'operatingSystem'
     */
    @Test
    void operatingSystemTest() {
        // TODO: test operatingSystem
    }

    /**
     * Test the property 'availableMemory'
     */
    @Test
    void availableMemoryTest() {
        // TODO: test availableMemory
    }

}
