/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SupervisorRest
 */
class SupervisorRestTest {
    private final SupervisorRest model = new SupervisorRest();

    /**
     * Model tests for SupervisorRest
     */
    @Test
    void testSupervisorRest() {
        // TODO: test SupervisorRest
    }

    /**
     * Test the property 'nodeName'
     */
    @Test
    void nodeNameTest() {
        // TODO: test nodeName
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'physicalMemory'
     */
    @Test
    void physicalMemoryTest() {
        // TODO: test physicalMemory
    }

    /**
     * Test the property 'physicalCpu'
     */
    @Test
    void physicalCpuTest() {
        // TODO: test physicalCpu
    }

    /**
     * Test the property 'operatingSystem'
     */
    @Test
    void operatingSystemTest() {
        // TODO: test operatingSystem
    }

    /**
     * Test the property 'availableMemory'
     */
    @Test
    void availableMemoryTest() {
        // TODO: test availableMemory
    }

}
