name: Java CI with Maven

on: [push, manual]
push:
  branches: [main]

jobs:
  build:
    image: maven:3.9-eclipse-temurin-21
    cache:
      key: m2-jsupervisor
      paths: [.m2/repository]
    steps:
      - name: Checkout
        run: git clone --depth 1 https://github.com/alexmond/jsupervisor.git .
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Pdefault --no-transfer-progress -Dmaven.repo.local=.m2/repository
    artifacts:
      - "**/surefire-reports/TEST-*.xml"
