/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.alexmond.jsupervisor.client.model.Link;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * EntityModelProcessEventEntry
 */
@JsonPropertyOrder({
  EntityModelProcessEventEntry.JSON_PROPERTY_ID,
  EntityModelProcessEventEntry.JSON_PROPERTY_PID,
  EntityModelProcessEventEntry.JSON_PROPERTY_EVENT_TIME,
  EntityModelProcessEventEntry.JSON_PROPERTY_PROCESS_NAME,
  EntityModelProcessEventEntry.JSON_PROPERTY_START_TIME,
  EntityModelProcessEventEntry.JSON_PROPERTY_END_TIME,
  EntityModelProcessEventEntry.JSON_PROPERTY_EXIT_CODE,
  EntityModelProcessEventEntry.JSON_PROPERTY_NEW_STATUS,
  EntityModelProcessEventEntry.JSON_PROPERTY_OLD_STATUS,
  EntityModelProcessEventEntry.JSON_PROPERTY_PROCESS_UPTIME,
  EntityModelProcessEventEntry.JSON_PROPERTY_LINKS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class EntityModelProcessEventEntry {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_PID = "pid";
  @jakarta.annotation.Nullable
  private Long pid;

  public static final String JSON_PROPERTY_EVENT_TIME = "eventTime";
  @jakarta.annotation.Nullable
  private OffsetDateTime eventTime;

  public static final String JSON_PROPERTY_PROCESS_NAME = "processName";
  @jakarta.annotation.Nullable
  private String processName;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  @jakarta.annotation.Nullable
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  @jakarta.annotation.Nullable
  private OffsetDateTime endTime;

  public static final String JSON_PROPERTY_EXIT_CODE = "exitCode";
  @jakarta.annotation.Nullable
  private Integer exitCode;

  /**
   * Gets or Sets newStatus
   */
  public enum NewStatusEnum {
    NOT_STARTED(String.valueOf("not_started")),
    
    RUNNING(String.valueOf("running")),
    
    FINISHED(String.valueOf("finished")),
    
    UNKNOWN(String.valueOf("unknown")),
    
    FAILED(String.valueOf("failed")),
    
    FAILED_TO_START(String.valueOf("failed_to_start")),
    
    STOPPED(String.valueOf("stopped")),
    
    STOPPING(String.valueOf("stopping")),
    
    ABORTED(String.valueOf("aborted")),
    
    STARTING(String.valueOf("starting")),
    
    HEALTHY(String.valueOf("healthy")),
    
    UNHEALTHY(String.valueOf("unhealthy"));

    private String value;

    NewStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static NewStatusEnum fromValue(String value) {
      for (NewStatusEnum b : NewStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_NEW_STATUS = "newStatus";
  @jakarta.annotation.Nullable
  private NewStatusEnum newStatus;

  /**
   * Gets or Sets oldStatus
   */
  public enum OldStatusEnum {
    NOT_STARTED(String.valueOf("not_started")),
    
    RUNNING(String.valueOf("running")),
    
    FINISHED(String.valueOf("finished")),
    
    UNKNOWN(String.valueOf("unknown")),
    
    FAILED(String.valueOf("failed")),
    
    FAILED_TO_START(String.valueOf("failed_to_start")),
    
    STOPPED(String.valueOf("stopped")),
    
    STOPPING(String.valueOf("stopping")),
    
    ABORTED(String.valueOf("aborted")),
    
    STARTING(String.valueOf("starting")),
    
    HEALTHY(String.valueOf("healthy")),
    
    UNHEALTHY(String.valueOf("unhealthy"));

    private String value;

    OldStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OldStatusEnum fromValue(String value) {
      for (OldStatusEnum b : OldStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OLD_STATUS = "oldStatus";
  @jakarta.annotation.Nullable
  private OldStatusEnum oldStatus;

  public static final String JSON_PROPERTY_PROCESS_UPTIME = "processUptime";
  @jakarta.annotation.Nullable
  private String processUptime;

  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nullable
  private List<@Valid Link> links = new ArrayList<>();

  public EntityModelProcessEventEntry() {
  }

  public EntityModelProcessEventEntry id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public EntityModelProcessEventEntry pid(@jakarta.annotation.Nullable Long pid) {
    
    this.pid = pid;
    return this;
  }

  /**
   * Get pid
   * @return pid
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_PID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPid() {
    return pid;
  }


  @JsonProperty(value = JSON_PROPERTY_PID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPid(@jakarta.annotation.Nullable Long pid) {
    this.pid = pid;
  }

  public EntityModelProcessEventEntry eventTime(@jakarta.annotation.Nullable OffsetDateTime eventTime) {
    
    this.eventTime = eventTime;
    return this;
  }

  /**
   * Get eventTime
   * @return eventTime
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_EVENT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEventTime() {
    return eventTime;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventTime(@jakarta.annotation.Nullable OffsetDateTime eventTime) {
    this.eventTime = eventTime;
  }

  public EntityModelProcessEventEntry processName(@jakarta.annotation.Nullable String processName) {
    
    this.processName = processName;
    return this;
  }

  /**
   * Get processName
   * @return processName
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_PROCESS_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessName() {
    return processName;
  }


  @JsonProperty(value = JSON_PROPERTY_PROCESS_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessName(@jakarta.annotation.Nullable String processName) {
    this.processName = processName;
  }

  public EntityModelProcessEventEntry startTime(@jakarta.annotation.Nullable OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

  /**
   * Get startTime
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public EntityModelProcessEventEntry endTime(@jakarta.annotation.Nullable OffsetDateTime endTime) {
    
    this.endTime = endTime;
    return this;
  }

  /**
   * Get endTime
   * @return endTime
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEndTime() {
    return endTime;
  }


  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(@jakarta.annotation.Nullable OffsetDateTime endTime) {
    this.endTime = endTime;
  }

  public EntityModelProcessEventEntry exitCode(@jakarta.annotation.Nullable Integer exitCode) {
    
    this.exitCode = exitCode;
    return this;
  }

  /**
   * Get exitCode
   * @return exitCode
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_EXIT_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExitCode() {
    return exitCode;
  }


  @JsonProperty(value = JSON_PROPERTY_EXIT_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExitCode(@jakarta.annotation.Nullable Integer exitCode) {
    this.exitCode = exitCode;
  }

  public EntityModelProcessEventEntry newStatus(@jakarta.annotation.Nullable NewStatusEnum newStatus) {
    
    this.newStatus = newStatus;
    return this;
  }

  /**
   * Get newStatus
   * @return newStatus
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_NEW_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NewStatusEnum getNewStatus() {
    return newStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_NEW_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewStatus(@jakarta.annotation.Nullable NewStatusEnum newStatus) {
    this.newStatus = newStatus;
  }

  public EntityModelProcessEventEntry oldStatus(@jakarta.annotation.Nullable OldStatusEnum oldStatus) {
    
    this.oldStatus = oldStatus;
    return this;
  }

  /**
   * Get oldStatus
   * @return oldStatus
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_OLD_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OldStatusEnum getOldStatus() {
    return oldStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_OLD_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOldStatus(@jakarta.annotation.Nullable OldStatusEnum oldStatus) {
    this.oldStatus = oldStatus;
  }

  public EntityModelProcessEventEntry processUptime(@jakarta.annotation.Nullable String processUptime) {
    
    this.processUptime = processUptime;
    return this;
  }

  /**
   * Get processUptime
   * @return processUptime
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_PROCESS_UPTIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessUptime() {
    return processUptime;
  }


  @JsonProperty(value = JSON_PROPERTY_PROCESS_UPTIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessUptime(@jakarta.annotation.Nullable String processUptime) {
    this.processUptime = processUptime;
  }

  public EntityModelProcessEventEntry links(@jakarta.annotation.Nullable List<@Valid Link> links) {
    
    this.links = links;
    return this;
  }

  public EntityModelProcessEventEntry addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid Link> getLinks() {
    return links;
  }


  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@jakarta.annotation.Nullable List<@Valid Link> links) {
    this.links = links;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityModelProcessEventEntry entityModelProcessEventEntry = (EntityModelProcessEventEntry) o;
    return Objects.equals(this.id, entityModelProcessEventEntry.id) &&
        Objects.equals(this.pid, entityModelProcessEventEntry.pid) &&
        Objects.equals(this.eventTime, entityModelProcessEventEntry.eventTime) &&
        Objects.equals(this.processName, entityModelProcessEventEntry.processName) &&
        Objects.equals(this.startTime, entityModelProcessEventEntry.startTime) &&
        Objects.equals(this.endTime, entityModelProcessEventEntry.endTime) &&
        Objects.equals(this.exitCode, entityModelProcessEventEntry.exitCode) &&
        Objects.equals(this.newStatus, entityModelProcessEventEntry.newStatus) &&
        Objects.equals(this.oldStatus, entityModelProcessEventEntry.oldStatus) &&
        Objects.equals(this.processUptime, entityModelProcessEventEntry.processUptime) &&
        Objects.equals(this.links, entityModelProcessEventEntry.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, pid, eventTime, processName, startTime, endTime, exitCode, newStatus, oldStatus, processUptime, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityModelProcessEventEntry {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    processName: ").append(toIndentedString(processName)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    exitCode: ").append(toIndentedString(exitCode)).append("\n");
    sb.append("    newStatus: ").append(toIndentedString(newStatus)).append("\n");
    sb.append("    oldStatus: ").append(toIndentedString(oldStatus)).append("\n");
    sb.append("    processUptime: ").append(toIndentedString(processUptime)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `pid` to the URL query string
    if (getPid() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%spid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPid()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `eventTime` to the URL query string
    if (getEventTime() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%seventTime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEventTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `processName` to the URL query string
    if (getProcessName() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sprocessName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getProcessName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `startTime` to the URL query string
    if (getStartTime() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sstartTime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStartTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `endTime` to the URL query string
    if (getEndTime() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sendTime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEndTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `exitCode` to the URL query string
    if (getExitCode() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sexitCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExitCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `newStatus` to the URL query string
    if (getNewStatus() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%snewStatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNewStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `oldStatus` to the URL query string
    if (getOldStatus() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%soldStatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getOldStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `processUptime` to the URL query string
    if (getProcessUptime() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sprocessUptime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getProcessUptime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `links` to the URL query string
    if (getLinks() != null) {
      for (int i = 0; i < getLinks().size(); i++) {
        if (getLinks().get(i) != null) {
          joiner.add(getLinks().get(i).toUrlQueryString(String.format(Locale.ROOT, "%slinks%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

