/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.alexmond.jsupervisor.client.model.AbstractJsonSchemaPropertyObject;
import org.alexmond.jsupervisor.client.model.Item;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * JsonSchema
 */
@JsonPropertyOrder({
  JsonSchema.JSON_PROPERTY_TITLE,
  JsonSchema.JSON_PROPERTY_DESCRIPTION,
  JsonSchema.JSON_PROPERTY_PROPERTIES,
  JsonSchema.JSON_PROPERTY_REQUIRED_PROPERTIES,
  JsonSchema.JSON_PROPERTY_DEFINITIONS,
  JsonSchema.JSON_PROPERTY_TYPE,
  JsonSchema.JSON_PROPERTY_$_SCHEMA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class JsonSchema {
  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @jakarta.annotation.Nullable
  private Map<String, AbstractJsonSchemaPropertyObject> properties = new HashMap<>();

  public static final String JSON_PROPERTY_REQUIRED_PROPERTIES = "requiredProperties";
  @jakarta.annotation.Nullable
  private List<String> requiredProperties = new ArrayList<>();

  public static final String JSON_PROPERTY_DEFINITIONS = "definitions";
  @jakarta.annotation.Nullable
  private Map<String, Item> definitions = new HashMap<>();

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_$_SCHEMA = "$schema";
  @jakarta.annotation.Nullable
  private String $schema;

  public JsonSchema() {
  }

  public JsonSchema title(@jakarta.annotation.Nullable String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = title;
  }

  public JsonSchema description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public JsonSchema properties(@jakarta.annotation.Nullable Map<String, AbstractJsonSchemaPropertyObject> properties) {
    
    this.properties = properties;
    return this;
  }

  public JsonSchema putPropertiesItem(String key, AbstractJsonSchemaPropertyObject propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PROPERTIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, AbstractJsonSchemaPropertyObject> getProperties() {
    return properties;
  }


  @JsonProperty(value = JSON_PROPERTY_PROPERTIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(@jakarta.annotation.Nullable Map<String, AbstractJsonSchemaPropertyObject> properties) {
    this.properties = properties;
  }

  public JsonSchema requiredProperties(@jakarta.annotation.Nullable List<String> requiredProperties) {
    
    this.requiredProperties = requiredProperties;
    return this;
  }

  public JsonSchema addRequiredPropertiesItem(String requiredPropertiesItem) {
    if (this.requiredProperties == null) {
      this.requiredProperties = new ArrayList<>();
    }
    this.requiredProperties.add(requiredPropertiesItem);
    return this;
  }

  /**
   * Get requiredProperties
   * @return requiredProperties
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_REQUIRED_PROPERTIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRequiredProperties() {
    return requiredProperties;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIRED_PROPERTIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequiredProperties(@jakarta.annotation.Nullable List<String> requiredProperties) {
    this.requiredProperties = requiredProperties;
  }

  public JsonSchema definitions(@jakarta.annotation.Nullable Map<String, Item> definitions) {
    
    this.definitions = definitions;
    return this;
  }

  public JsonSchema putDefinitionsItem(String key, Item definitionsItem) {
    if (this.definitions == null) {
      this.definitions = new HashMap<>();
    }
    this.definitions.put(key, definitionsItem);
    return this;
  }

  /**
   * Get definitions
   * @return definitions
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_DEFINITIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Item> getDefinitions() {
    return definitions;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFINITIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefinitions(@jakarta.annotation.Nullable Map<String, Item> definitions) {
    this.definitions = definitions;
  }

  public JsonSchema type(@jakarta.annotation.Nullable String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = type;
  }

  public JsonSchema $schema(@jakarta.annotation.Nullable String $schema) {
    
    this.$schema = $schema;
    return this;
  }

  /**
   * Get $schema
   * @return $schema
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_$_SCHEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String get$Schema() {
    return $schema;
  }


  @JsonProperty(value = JSON_PROPERTY_$_SCHEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void set$Schema(@jakarta.annotation.Nullable String $schema) {
    this.$schema = $schema;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonSchema jsonSchema = (JsonSchema) o;
    return Objects.equals(this.title, jsonSchema.title) &&
        Objects.equals(this.description, jsonSchema.description) &&
        Objects.equals(this.properties, jsonSchema.properties) &&
        Objects.equals(this.requiredProperties, jsonSchema.requiredProperties) &&
        Objects.equals(this.definitions, jsonSchema.definitions) &&
        Objects.equals(this.type, jsonSchema.type) &&
        Objects.equals(this.$schema, jsonSchema.$schema);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, properties, requiredProperties, definitions, type, $schema);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonSchema {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    requiredProperties: ").append(toIndentedString(requiredProperties)).append("\n");
    sb.append("    definitions: ").append(toIndentedString(definitions)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    $schema: ").append(toIndentedString($schema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `title` to the URL query string
    if (getTitle() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%stitle%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTitle()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `properties` to the URL query string
    if (getProperties() != null) {
      for (String _key : getProperties().keySet()) {
        if (getProperties().get(_key) != null) {
          joiner.add(getProperties().get(_key).toUrlQueryString(String.format(Locale.ROOT, "%sproperties%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    // add `requiredProperties` to the URL query string
    if (getRequiredProperties() != null) {
      for (int i = 0; i < getRequiredProperties().size(); i++) {
        try {
          joiner.add(String.format(Locale.ROOT, "%srequiredProperties%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getRequiredProperties().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `definitions` to the URL query string
    if (getDefinitions() != null) {
      for (String _key : getDefinitions().keySet()) {
        if (getDefinitions().get(_key) != null) {
          joiner.add(getDefinitions().get(_key).toUrlQueryString(String.format(Locale.ROOT, "%sdefinitions%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `$schema` to the URL query string
    if (get$Schema() != null) {
      try {
        joiner.add(String.format(Locale.ROOT, "%s$schema%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(get$Schema()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

