/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Locale;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Link
 */
@JsonPropertyOrder({
        Link.JSON_PROPERTY_REL,
        Link.JSON_PROPERTY_HREF,
        Link.JSON_PROPERTY_HREFLANG,
        Link.JSON_PROPERTY_MEDIA,
        Link.JSON_PROPERTY_TITLE,
        Link.JSON_PROPERTY_TYPE,
        Link.JSON_PROPERTY_DEPRECATION,
        Link.JSON_PROPERTY_PROFILE,
        Link.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Link {
    public static final String JSON_PROPERTY_REL = "rel";
    public static final String JSON_PROPERTY_HREF = "href";
    public static final String JSON_PROPERTY_HREFLANG = "hreflang";
    public static final String JSON_PROPERTY_MEDIA = "media";
    public static final String JSON_PROPERTY_TITLE = "title";
    public static final String JSON_PROPERTY_TYPE = "type";
    public static final String JSON_PROPERTY_DEPRECATION = "deprecation";
    public static final String JSON_PROPERTY_PROFILE = "profile";
    public static final String JSON_PROPERTY_NAME = "name";
    @jakarta.annotation.Nullable
    private String rel;
    @jakarta.annotation.Nullable
    private String href;
    @jakarta.annotation.Nullable
    private String hreflang;
    @jakarta.annotation.Nullable
    private String media;
    @jakarta.annotation.Nullable
    private String title;
    @jakarta.annotation.Nullable
    private String type;
    @jakarta.annotation.Nullable
    private String deprecation;
    @jakarta.annotation.Nullable
    private String profile;
    @jakarta.annotation.Nullable
    private String name;

    public Link() {
    }

    public Link rel(@jakarta.annotation.Nullable String rel) {

        this.rel = rel;
        return this;
    }

    /**
     * Get rel
     *
     * @return rel
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_REL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getRel() {
        return rel;
    }


    @JsonProperty(value = JSON_PROPERTY_REL, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRel(@jakarta.annotation.Nullable String rel) {
        this.rel = rel;
    }

    public Link href(@jakarta.annotation.Nullable String href) {

        this.href = href;
        return this;
    }

    /**
     * Get href
     *
     * @return href
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_HREF, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getHref() {
        return href;
    }


    @JsonProperty(value = JSON_PROPERTY_HREF, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHref(@jakarta.annotation.Nullable String href) {
        this.href = href;
    }

    public Link hreflang(@jakarta.annotation.Nullable String hreflang) {

        this.hreflang = hreflang;
        return this;
    }

    /**
     * Get hreflang
     *
     * @return hreflang
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_HREFLANG, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getHreflang() {
        return hreflang;
    }


    @JsonProperty(value = JSON_PROPERTY_HREFLANG, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHreflang(@jakarta.annotation.Nullable String hreflang) {
        this.hreflang = hreflang;
    }

    public Link media(@jakarta.annotation.Nullable String media) {

        this.media = media;
        return this;
    }

    /**
     * Get media
     *
     * @return media
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_MEDIA, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMedia() {
        return media;
    }


    @JsonProperty(value = JSON_PROPERTY_MEDIA, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMedia(@jakarta.annotation.Nullable String media) {
        this.media = media;
    }

    public Link title(@jakarta.annotation.Nullable String title) {

        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTitle() {
        return title;
    }


    @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTitle(@jakarta.annotation.Nullable String title) {
        this.title = title;
    }

    public Link type(@jakarta.annotation.Nullable String type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getType() {
        return type;
    }


    @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(@jakarta.annotation.Nullable String type) {
        this.type = type;
    }

    public Link deprecation(@jakarta.annotation.Nullable String deprecation) {

        this.deprecation = deprecation;
        return this;
    }

    /**
     * Get deprecation
     *
     * @return deprecation
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_DEPRECATION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeprecation() {
        return deprecation;
    }


    @JsonProperty(value = JSON_PROPERTY_DEPRECATION, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeprecation(@jakarta.annotation.Nullable String deprecation) {
        this.deprecation = deprecation;
    }

    public Link profile(@jakarta.annotation.Nullable String profile) {

        this.profile = profile;
        return this;
    }

    /**
     * Get profile
     *
     * @return profile
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_PROFILE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getProfile() {
        return profile;
    }


    @JsonProperty(value = JSON_PROPERTY_PROFILE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProfile(@jakarta.annotation.Nullable String profile) {
        this.profile = profile;
    }

    public Link name(@jakarta.annotation.Nullable String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }


    @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(@jakarta.annotation.Nullable String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Link link = (Link) o;
        return Objects.equals(this.rel, link.rel) &&
                Objects.equals(this.href, link.href) &&
                Objects.equals(this.hreflang, link.hreflang) &&
                Objects.equals(this.media, link.media) &&
                Objects.equals(this.title, link.title) &&
                Objects.equals(this.type, link.type) &&
                Objects.equals(this.deprecation, link.deprecation) &&
                Objects.equals(this.profile, link.profile) &&
                Objects.equals(this.name, link.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(rel, href, hreflang, media, title, type, deprecation, profile, name);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Link {\n");
        sb.append("    rel: ").append(toIndentedString(rel)).append("\n");
        sb.append("    href: ").append(toIndentedString(href)).append("\n");
        sb.append("    hreflang: ").append(toIndentedString(hreflang)).append("\n");
        sb.append("    media: ").append(toIndentedString(media)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    deprecation: ").append(toIndentedString(deprecation)).append("\n");
        sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `rel` to the URL query string
        if (getRel() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%srel%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRel()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `href` to the URL query string
        if (getHref() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%shref%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHref()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `hreflang` to the URL query string
        if (getHreflang() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%shreflang%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHreflang()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `media` to the URL query string
        if (getMedia() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%smedia%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMedia()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `title` to the URL query string
        if (getTitle() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%stitle%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTitle()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `type` to the URL query string
        if (getType() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `deprecation` to the URL query string
        if (getDeprecation() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%sdeprecation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeprecation()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `profile` to the URL query string
        if (getProfile() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%sprofile%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getProfile()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `name` to the URL query string
        if (getName() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        return joiner.toString();
    }

}

