/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.alexmond.jsupervisor.client.model.EntityModelProcessEventEntry;
import org.alexmond.jsupervisor.client.model.Link;
import org.alexmond.jsupervisor.client.model.PageMetadata;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * PagedModelEntityModelProcessEventEntry
 */
@JsonPropertyOrder({
  PagedModelEntityModelProcessEventEntry.JSON_PROPERTY_LINKS,
  PagedModelEntityModelProcessEventEntry.JSON_PROPERTY_CONTENT,
  PagedModelEntityModelProcessEventEntry.JSON_PROPERTY_PAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class PagedModelEntityModelProcessEventEntry {
  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nullable
  private List<@Valid Link> links = new ArrayList<>();

  public static final String JSON_PROPERTY_CONTENT = "content";
  @jakarta.annotation.Nullable
  private List<@Valid EntityModelProcessEventEntry> content = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGE = "page";
  @jakarta.annotation.Nullable
  private PageMetadata page;

  public PagedModelEntityModelProcessEventEntry() {
  }

  public PagedModelEntityModelProcessEventEntry links(@jakarta.annotation.Nullable List<@Valid Link> links) {
    
    this.links = links;
    return this;
  }

  public PagedModelEntityModelProcessEventEntry addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid Link> getLinks() {
    return links;
  }


  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@jakarta.annotation.Nullable List<@Valid Link> links) {
    this.links = links;
  }

  public PagedModelEntityModelProcessEventEntry content(@jakarta.annotation.Nullable List<@Valid EntityModelProcessEventEntry> content) {
    
    this.content = content;
    return this;
  }

  public PagedModelEntityModelProcessEventEntry addContentItem(EntityModelProcessEventEntry contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid EntityModelProcessEventEntry> getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(@jakarta.annotation.Nullable List<@Valid EntityModelProcessEventEntry> content) {
    this.content = content;
  }

  public PagedModelEntityModelProcessEventEntry page(@jakarta.annotation.Nullable PageMetadata page) {
    
    this.page = page;
    return this;
  }

  /**
   * Get page
   * @return page
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PageMetadata getPage() {
    return page;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(@jakarta.annotation.Nullable PageMetadata page) {
    this.page = page;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedModelEntityModelProcessEventEntry pagedModelEntityModelProcessEventEntry = (PagedModelEntityModelProcessEventEntry) o;
    return Objects.equals(this.links, pagedModelEntityModelProcessEventEntry.links) &&
        Objects.equals(this.content, pagedModelEntityModelProcessEventEntry.content) &&
        Objects.equals(this.page, pagedModelEntityModelProcessEventEntry.page);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, content, page);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedModelEntityModelProcessEventEntry {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `links` to the URL query string
    if (getLinks() != null) {
      for (int i = 0; i < getLinks().size(); i++) {
        if (getLinks().get(i) != null) {
          joiner.add(getLinks().get(i).toUrlQueryString(String.format(Locale.ROOT, "%slinks%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `content` to the URL query string
    if (getContent() != null) {
      for (int i = 0; i < getContent().size(); i++) {
        if (getContent().get(i) != null) {
          joiner.add(getContent().get(i).toUrlQueryString(String.format(Locale.ROOT, "%scontent%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `page` to the URL query string
    if (getPage() != null) {
      joiner.add(getPage().toUrlQueryString(prefix + "page" + suffix));
    }

    return joiner.toString();
  }

}

