/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.*;

/**
 * Page
 */
@JsonPropertyOrder({
        Page.JSON_PROPERTY_TOTAL_PAGES,
        Page.JSON_PROPERTY_TOTAL_ELEMENTS,
        Page.JSON_PROPERTY_FIRST,
        Page.JSON_PROPERTY_LAST,
        Page.JSON_PROPERTY_SIZE,
        Page.JSON_PROPERTY_CONTENT,
        Page.JSON_PROPERTY_NUMBER,
        Page.JSON_PROPERTY_SORT,
        Page.JSON_PROPERTY_PAGEABLE,
        Page.JSON_PROPERTY_NUMBER_OF_ELEMENTS,
        Page.JSON_PROPERTY_EMPTY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Page {
    public static final String JSON_PROPERTY_TOTAL_PAGES = "totalPages";
    public static final String JSON_PROPERTY_TOTAL_ELEMENTS = "totalElements";
    public static final String JSON_PROPERTY_FIRST = "first";
    public static final String JSON_PROPERTY_LAST = "last";
    public static final String JSON_PROPERTY_SIZE = "size";
    public static final String JSON_PROPERTY_CONTENT = "content";
    public static final String JSON_PROPERTY_NUMBER = "number";
    public static final String JSON_PROPERTY_SORT = "sort";
    public static final String JSON_PROPERTY_PAGEABLE = "pageable";
    public static final String JSON_PROPERTY_NUMBER_OF_ELEMENTS = "numberOfElements";
    public static final String JSON_PROPERTY_EMPTY = "empty";
    @jakarta.annotation.Nullable
    private Integer totalPages;
    @jakarta.annotation.Nullable
    private Long totalElements;
    @jakarta.annotation.Nullable
    private Boolean first;
    @jakarta.annotation.Nullable
    private Boolean last;
    @jakarta.annotation.Nullable
    private Integer size;
    @jakarta.annotation.Nullable
    private List<Object> content = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Integer number;
    @jakarta.annotation.Nullable
    private SortObject sort;
    @jakarta.annotation.Nullable
    private PageableObject pageable;
    @jakarta.annotation.Nullable
    private Integer numberOfElements;
    @jakarta.annotation.Nullable
    private Boolean empty;

    public Page() {
    }

    public Page totalPages(@jakarta.annotation.Nullable Integer totalPages) {

        this.totalPages = totalPages;
        return this;
    }

    /**
     * Get totalPages
     *
     * @return totalPages
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_TOTAL_PAGES, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getTotalPages() {
        return totalPages;
    }


    @JsonProperty(value = JSON_PROPERTY_TOTAL_PAGES, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTotalPages(@jakarta.annotation.Nullable Integer totalPages) {
        this.totalPages = totalPages;
    }

    public Page totalElements(@jakarta.annotation.Nullable Long totalElements) {

        this.totalElements = totalElements;
        return this;
    }

    /**
     * Get totalElements
     *
     * @return totalElements
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_TOTAL_ELEMENTS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getTotalElements() {
        return totalElements;
    }


    @JsonProperty(value = JSON_PROPERTY_TOTAL_ELEMENTS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTotalElements(@jakarta.annotation.Nullable Long totalElements) {
        this.totalElements = totalElements;
    }

    public Page first(@jakarta.annotation.Nullable Boolean first) {

        this.first = first;
        return this;
    }

    /**
     * Get first
     *
     * @return first
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_FIRST, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getFirst() {
        return first;
    }


    @JsonProperty(value = JSON_PROPERTY_FIRST, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFirst(@jakarta.annotation.Nullable Boolean first) {
        this.first = first;
    }

    public Page last(@jakarta.annotation.Nullable Boolean last) {

        this.last = last;
        return this;
    }

    /**
     * Get last
     *
     * @return last
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_LAST, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getLast() {
        return last;
    }


    @JsonProperty(value = JSON_PROPERTY_LAST, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLast(@jakarta.annotation.Nullable Boolean last) {
        this.last = last;
    }

    public Page size(@jakarta.annotation.Nullable Integer size) {

        this.size = size;
        return this;
    }

    /**
     * Get size
     *
     * @return size
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_SIZE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getSize() {
        return size;
    }


    @JsonProperty(value = JSON_PROPERTY_SIZE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSize(@jakarta.annotation.Nullable Integer size) {
        this.size = size;
    }

    public Page content(@jakarta.annotation.Nullable List<Object> content) {

        this.content = content;
        return this;
    }

    public Page addContentItem(Object contentItem) {
        if (this.content == null) {
            this.content = new ArrayList<>();
        }
        this.content.add(contentItem);
        return this;
    }

    /**
     * Get content
     *
     * @return content
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Object> getContent() {
        return content;
    }


    @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setContent(@jakarta.annotation.Nullable List<Object> content) {
        this.content = content;
    }

    public Page number(@jakarta.annotation.Nullable Integer number) {

        this.number = number;
        return this;
    }

    /**
     * Get number
     *
     * @return number
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_NUMBER, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getNumber() {
        return number;
    }


    @JsonProperty(value = JSON_PROPERTY_NUMBER, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNumber(@jakarta.annotation.Nullable Integer number) {
        this.number = number;
    }

    public Page sort(@jakarta.annotation.Nullable SortObject sort) {

        this.sort = sort;
        return this;
    }

    /**
     * Get sort
     *
     * @return sort
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(value = JSON_PROPERTY_SORT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public SortObject getSort() {
        return sort;
    }


    @JsonProperty(value = JSON_PROPERTY_SORT, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSort(@jakarta.annotation.Nullable SortObject sort) {
        this.sort = sort;
    }

    public Page pageable(@jakarta.annotation.Nullable PageableObject pageable) {

        this.pageable = pageable;
        return this;
    }

    /**
     * Get pageable
     *
     * @return pageable
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(value = JSON_PROPERTY_PAGEABLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PageableObject getPageable() {
        return pageable;
    }


    @JsonProperty(value = JSON_PROPERTY_PAGEABLE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPageable(@jakarta.annotation.Nullable PageableObject pageable) {
        this.pageable = pageable;
    }

    public Page numberOfElements(@jakarta.annotation.Nullable Integer numberOfElements) {

        this.numberOfElements = numberOfElements;
        return this;
    }

    /**
     * Get numberOfElements
     *
     * @return numberOfElements
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_NUMBER_OF_ELEMENTS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getNumberOfElements() {
        return numberOfElements;
    }


    @JsonProperty(value = JSON_PROPERTY_NUMBER_OF_ELEMENTS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNumberOfElements(@jakarta.annotation.Nullable Integer numberOfElements) {
        this.numberOfElements = numberOfElements;
    }

    public Page empty(@jakarta.annotation.Nullable Boolean empty) {

        this.empty = empty;
        return this;
    }

    /**
     * Get empty
     *
     * @return empty
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_EMPTY, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getEmpty() {
        return empty;
    }


    @JsonProperty(value = JSON_PROPERTY_EMPTY, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEmpty(@jakarta.annotation.Nullable Boolean empty) {
        this.empty = empty;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Page page = (Page) o;
        return Objects.equals(this.totalPages, page.totalPages) &&
                Objects.equals(this.totalElements, page.totalElements) &&
                Objects.equals(this.first, page.first) &&
                Objects.equals(this.last, page.last) &&
                Objects.equals(this.size, page.size) &&
                Objects.equals(this.content, page.content) &&
                Objects.equals(this.number, page.number) &&
                Objects.equals(this.sort, page.sort) &&
                Objects.equals(this.pageable, page.pageable) &&
                Objects.equals(this.numberOfElements, page.numberOfElements) &&
                Objects.equals(this.empty, page.empty);
    }

    @Override
    public int hashCode() {
        return Objects.hash(totalPages, totalElements, first, last, size, content, number, sort, pageable, numberOfElements, empty);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Page {\n");
        sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
        sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
        sb.append("    first: ").append(toIndentedString(first)).append("\n");
        sb.append("    last: ").append(toIndentedString(last)).append("\n");
        sb.append("    size: ").append(toIndentedString(size)).append("\n");
        sb.append("    content: ").append(toIndentedString(content)).append("\n");
        sb.append("    number: ").append(toIndentedString(number)).append("\n");
        sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
        sb.append("    pageable: ").append(toIndentedString(pageable)).append("\n");
        sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
        sb.append("    empty: ").append(toIndentedString(empty)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `totalPages` to the URL query string
        if (getTotalPages() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%stotalPages%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotalPages()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `totalElements` to the URL query string
        if (getTotalElements() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%stotalElements%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotalElements()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `first` to the URL query string
        if (getFirst() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%sfirst%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFirst()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `last` to the URL query string
        if (getLast() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%slast%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLast()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `size` to the URL query string
        if (getSize() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%ssize%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSize()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `content` to the URL query string
        if (getContent() != null) {
            for (int i = 0; i < getContent().size(); i++) {
                try {
                    joiner.add(String.format(Locale.ROOT, "%scontent%s%s=%s", prefix, suffix,
                            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
                            URLEncoder.encode(String.valueOf(getContent().get(i)), "UTF-8").replaceAll("\\+", "%20")));
                } catch (UnsupportedEncodingException e) {
                    // Should never happen, UTF-8 is always supported
                    throw new RuntimeException(e);
                }
            }
        }

        // add `number` to the URL query string
        if (getNumber() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%snumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNumber()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `sort` to the URL query string
        if (getSort() != null) {
            joiner.add(getSort().toUrlQueryString(prefix + "sort" + suffix));
        }

        // add `pageable` to the URL query string
        if (getPageable() != null) {
            joiner.add(getPageable().toUrlQueryString(prefix + "pageable" + suffix));
        }

        // add `numberOfElements` to the URL query string
        if (getNumberOfElements() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%snumberOfElements%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNumberOfElements()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `empty` to the URL query string
        if (getEmpty() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%sempty%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEmpty()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        return joiner.toString();
    }

}

