/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Locale;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * PageMetadata
 */
@JsonPropertyOrder({
        PageMetadata.JSON_PROPERTY_SIZE,
        PageMetadata.JSON_PROPERTY_TOTAL_ELEMENTS,
        PageMetadata.JSON_PROPERTY_TOTAL_PAGES,
        PageMetadata.JSON_PROPERTY_NUMBER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class PageMetadata {
    public static final String JSON_PROPERTY_SIZE = "size";
    public static final String JSON_PROPERTY_TOTAL_ELEMENTS = "totalElements";
    public static final String JSON_PROPERTY_TOTAL_PAGES = "totalPages";
    public static final String JSON_PROPERTY_NUMBER = "number";
    @jakarta.annotation.Nullable
    private Long size;
    @jakarta.annotation.Nullable
    private Long totalElements;
    @jakarta.annotation.Nullable
    private Long totalPages;
    @jakarta.annotation.Nullable
    private Long number;

    public PageMetadata() {
    }

    public PageMetadata size(@jakarta.annotation.Nullable Long size) {

        this.size = size;
        return this;
    }

    /**
     * Get size
     *
     * @return size
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_SIZE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getSize() {
        return size;
    }


    @JsonProperty(value = JSON_PROPERTY_SIZE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSize(@jakarta.annotation.Nullable Long size) {
        this.size = size;
    }

    public PageMetadata totalElements(@jakarta.annotation.Nullable Long totalElements) {

        this.totalElements = totalElements;
        return this;
    }

    /**
     * Get totalElements
     *
     * @return totalElements
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_TOTAL_ELEMENTS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getTotalElements() {
        return totalElements;
    }


    @JsonProperty(value = JSON_PROPERTY_TOTAL_ELEMENTS, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTotalElements(@jakarta.annotation.Nullable Long totalElements) {
        this.totalElements = totalElements;
    }

    public PageMetadata totalPages(@jakarta.annotation.Nullable Long totalPages) {

        this.totalPages = totalPages;
        return this;
    }

    /**
     * Get totalPages
     *
     * @return totalPages
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_TOTAL_PAGES, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getTotalPages() {
        return totalPages;
    }


    @JsonProperty(value = JSON_PROPERTY_TOTAL_PAGES, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTotalPages(@jakarta.annotation.Nullable Long totalPages) {
        this.totalPages = totalPages;
    }

    public PageMetadata number(@jakarta.annotation.Nullable Long number) {

        this.number = number;
        return this;
    }

    /**
     * Get number
     *
     * @return number
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_NUMBER, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getNumber() {
        return number;
    }


    @JsonProperty(value = JSON_PROPERTY_NUMBER, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNumber(@jakarta.annotation.Nullable Long number) {
        this.number = number;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PageMetadata pageMetadata = (PageMetadata) o;
        return Objects.equals(this.size, pageMetadata.size) &&
                Objects.equals(this.totalElements, pageMetadata.totalElements) &&
                Objects.equals(this.totalPages, pageMetadata.totalPages) &&
                Objects.equals(this.number, pageMetadata.number);
    }

    @Override
    public int hashCode() {
        return Objects.hash(size, totalElements, totalPages, number);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PageMetadata {\n");
        sb.append("    size: ").append(toIndentedString(size)).append("\n");
        sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
        sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
        sb.append("    number: ").append(toIndentedString(number)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `size` to the URL query string
        if (getSize() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%ssize%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSize()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `totalElements` to the URL query string
        if (getTotalElements() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%stotalElements%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotalElements()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `totalPages` to the URL query string
        if (getTotalPages() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%stotalPages%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotalPages()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `number` to the URL query string
        if (getNumber() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%snumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNumber()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        return joiner.toString();
    }

}

