/*
 * JSupervisor REST API
 * JSupervisor is a process management and monitoring service that provides comprehensive control over application processes. This API enables you to:  - Start, stop, and restart processes individually or in bulk - Monitor process status and health - Retrieve process logs and statistics - Configure process behavior and auto-start settings  The API follows RESTful principles and returns JSON responses.
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: alex.mondshain@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.alexmond.jsupervisor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Locale;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * ResponseMessage
 */
@JsonPropertyOrder({
        ResponseMessage.JSON_PROPERTY_MESSAGE,
        ResponseMessage.JSON_PROPERTY_ERROR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ResponseMessage {
    public static final String JSON_PROPERTY_MESSAGE = "message";
    public static final String JSON_PROPERTY_ERROR = "error";
    @jakarta.annotation.Nullable
    private String message;
    @jakarta.annotation.Nullable
    private String error;

    public ResponseMessage() {
    }

    public ResponseMessage message(@jakarta.annotation.Nullable String message) {

        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMessage() {
        return message;
    }


    @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMessage(@jakarta.annotation.Nullable String message) {
        this.message = message;
    }

    public ResponseMessage error(@jakarta.annotation.Nullable String error) {

        this.error = error;
        return this;
    }

    /**
     * Get error
     *
     * @return error
     */
    @jakarta.annotation.Nullable

    @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getError() {
        return error;
    }


    @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setError(@jakarta.annotation.Nullable String error) {
        this.error = error;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResponseMessage responseMessage = (ResponseMessage) o;
        return Objects.equals(this.message, responseMessage.message) &&
                Objects.equals(this.error, responseMessage.error);
    }

    @Override
    public int hashCode() {
        return Objects.hash(message, error);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResponseMessage {\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    error: ").append(toIndentedString(error)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `message` to the URL query string
        if (getMessage() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%smessage%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMessage()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `error` to the URL query string
        if (getError() != null) {
            try {
                joiner.add(String.format(Locale.ROOT, "%serror%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getError()), "UTF-8").replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        return joiner.toString();
    }

}

